# Generated by Django 5.2 on 2025-05-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
