# Generated by Django 5.2 on 2025-05-19 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni_app', '0006_chatroom_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearedChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleared_at', models.DateTimeField(auto_now_add=True)),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni_app.alumni')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumni_app.chatroom')),
            ],
            options={
                'unique_together': {('alumni', 'chat_room')},
            },
        ),
    ]
